modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0-only"

issueTrackerURL = "https://github.com/Shihyeon/TabNameTag/issues"

[[mods]]
modId = "tabnametag"

displayName = "TabNameTag"

version = "${version}"

logoFile = "assets/tabnametag/icon.png"

authors = "Shihyeon"

description = '''

'''

modUrl = "https://modrinth.com/mod/tab-name-tag"
displayURL = "https://modrinth.com/mod/tab-name-tag"

[[mixins]]
config = "tabnametag.mixins.json"

[[mixins]]
config = "tabnametag.neoforge.mixins.json"

[[dependencies.tabnametag]]
modId = "neoforge"
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[${neoforge_version},)"
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "CLIENT" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.tabnametag]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"